### PR TITLE
Telemetry  DB service direct UDP connection

### PR DESCRIPTION
**Pull request by CatGarab**

### CODE REVIEW

**Comment by CatGarab** [comment]
[Telemetry DB: UDP socket to write to the database asynchronously](https://trello.com/c/kiL1NIWx/74-telemetry-db-udp-socket-to-write-to-the-database-asynchronously)

**Comment by jacoffey3** [comment]
@plauche I think it might be a bit much to ask at this point. Also @CatGarab, are the entries worked off round-robin from the 2 different sockets, or does one take priority?

**Comment by CatGarab** [comment]
@jacoffey3 it's not an official round-robin; it's two threads of the same priority level with a mutex, so it's just whichever thread gets triggered first (in theory, it'll go back and forth, though).

**Comment by jacoffey3** [comment]
> @jacoffey3 it's not an official round-robin; it's two threads of the same priority level with a mutex, so it's just whichever thread gets triggered first (in theory, it'll go back and forth, though).

That should be fine then! That'll keep anything from getting locked out.

**Pull request merged**
